kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: vulnerable-log4j
  namespace: vulnerable-cicd
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'vulnerable-log4j:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:11'
  source:
    type: Git
    git:
      uri: 'https://github.com/nmasse-itix/demo-rhacs.git'
      ref: main
    contextDir: log4shell/src
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
